# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 1, 19, 5, 56, 49, 924480))),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Employee')),
            ],
        ),
    ]
