# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20160126_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='fEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='flog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2016, 1, 27, 17, 50, 55, 532096))),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.fEmployee')),
            ],
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 17, 50, 55, 530434)),
        ),
    ]
