# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_auto_20160127_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flog',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 18, 46, 13, 99011)),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 27, 18, 46, 13, 96918)),
        ),
    ]
