# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_auto_20160127_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flog',
            name='date',
            field=models.DateField(default=datetime.date(2016, 1, 28)),
        ),
        migrations.AlterField(
            model_name='flog',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.FEmployee'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 28, 3, 47, 16, 627603)),
        ),
    ]
