# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0011_auto_20160128_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 2, 1))),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='flog',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='ename',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='fEmployee',
        ),
        migrations.DeleteModel(
            name='flog',
        ),
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
