# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0019_auto_20160203_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 4)),
        ),
    ]
